

const languageMap: Record<string, string> = {
  "zh": "中文",
  "es": "Español",
  "en": "English",
  "hi": "हिन्दी",
  "ar": "العربية",
  "bn": "বাংলা",
  "pt": "Português",
  "ru": "Русский",
  "ja": "日本語",
  "pa": "ਪੰਜਾਬੀ",
  "de": "Deutsch",
  "jv": "Basa Jawa",
  "ko": "한국어",
  "fr": "Français",
  "te": "తెలుగు",
  "mr": "मराठी",
  "tr": "Türkçe",
  "ta": "தமிழ்",
  "vi": "Tiếng Việt",
  "ur": "اردو",
  "it": "Italiano",
  "th": "ไทย",
  "gu": "ગુજરાતી",
  "pl": "Polski",
  "uk": "Українська",
  "fa": "فارسی",
  "ml": "മലയാളം",
  "kn": "ಕನ್ನಡ",
  "or": "ଓଡ଼ିଆ",
  "my": "မြန်မာ",
  "nl": "Nederlands",
  "sw": "Kiswahili",
  "ro": "Română",
  "su": "Basa Sunda",
  "am": "አማርኛ",
  "ha": "Hausa",
  "yo": "Yorùbá",
  "ig": "Igbo",
  "uz": "O'zbek",
  "sd": "سنڌي",
  "ne": "नेपाली",
  "si": "සිංහල",
  "km": "ខ្មែរ",
  "no": "Norsk",
  "fi": "Suomi",
  "da": "Dansk",
  "sv": "Svenska",
  "he": "עברית",
  "el": "Ελληνικά",
  "cs": "Čeština",
  "hu": "Magyar",
  "bg": "Български",
  "hr": "Hrvatski",
  "sk": "Slovenčina",
  "sl": "Slovenščina",
  "et": "Eesti",
  "lv": "Latviešu",
  "lt": "Lietuvių",
  "mk": "Македонски",
  "sq": "Shqip",
  "is": "Íslenska",
  "ga": "Gaeilge",
  "cy": "Cymraeg",
  "mt": "Malti",
  "eu": "Euskera",
  "ca": "Català",
  "gl": "Galego",
  "oc": "Occitan",
  "co": "Corsu",
  "br": "Brezhoneg",
  "rm": "Rumantsch",
  "lb": "Lëtzebuergesch",
  "fo": "Føroyskt",
  "gd": "Gàidhlig",
  "kw": "Kernowek",
  "mn": "Монгол",
  "bo": "བོད་སྐད་",
  "ug": "ئۇيغۇرچە",
  "kk": "Қазақша",
  "ky": "Кыргызча",
  "tg": "Тоҷикӣ",
  "tk": "Türkmençe",
  "az": "Azərbaycan",
  "ka": "ქართული",
  "hy": "Հայերեն",
  "be": "Беларуская",
  "ms": "Bahasa Melayu",
  "id": "Bahasa Indonesia",
  "tl": "Filipino",
  "mg": "Malagasy",
  "zu": "isiZulu",
  "xh": "isiXhosa",
  "af": "Afrikaans",
  "st": "Sesotho",
  "tn": "Setswana",
  "ve": "Tshivenḓa",
  "ts": "Xitsonga",
  "ss": "siSwati",
  "nr": "isiNdebele",
  "rw": "Kinyarwanda",
  "rn": "Kirundi",
  "so": "Soomaali",
  "ti": "ትግርኛ",
  "om": "Afaan Oromoo",
  "lg": "Luganda",
};


export function getLanguageFromCode(language_code: string): string {
  return languageMap[language_code] || "Unknown Language";
}

export function getLanguagesFromCode(language_codes: string[]): string[] {
  if (!language_codes || language_codes.length === 0) {
    return ["Unknown Language"];
  }
  return language_codes.map(lang => getLanguageFromCode(lang)).filter(lang => lang !== "Unknown Language");
}
