# Generated by Django 5.2.2 on 2025-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "ip_address",
                    models.GenericIPAddressField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=25565)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("players_online", models.PositiveIntegerField(default=0)),
                ("max_players", models.PositiveIntegerField(default=0)),
                ("motd", models.TextField(blank=True, null=True)),
                ("banner", models.URLField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("total_votes", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="servers", to="core.servertag"
                    ),
                ),
            ],
        ),
    ]
