# Generated by Django 5.2.2 on 2025-06-17 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("relevance", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address_java", models.URLField(blank=True, null=True)),
                ("ip_address_bedrock", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("players_online", models.PositiveIntegerField(default=0)),
                ("max_players", models.PositiveIntegerField(default=0)),
                ("motd", models.TextField(blank=True, null=True)),
                ("banner", models.URLField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("total_votes", models.PositiveIntegerField(default=0)),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "edition",
                    models.CharField(
                        choices=[
                            ("java", "Java Edition"),
                            ("bedrock", "Bedrock Edition"),
                            ("both", "Java + Bedrock"),
                        ],
                        default="java",
                        max_length=10,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("discord", models.URLField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="servers", to="core.servertag"
                    ),
                ),
            ],
        ),
    ]
