# Generated by Django 6.0.4 on 2026-04-09 05:45

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=25565)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('game_version', models.CharField(blank=True, default='', max_length=50)),
                ('edition', models.CharField(choices=[('java', 'Java'), ('bedrock', 'Bedrock'), ('both', 'Java & Bedrock')], default='java', max_length=10)),
                ('online_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('discord_url', models.URLField(blank=True, default='', max_length=500)),
                ('banner_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='servers', to='core.tag')),
            ],
            options={
                'ordering': ['-online_players'],
            },
        ),
        migrations.CreateModel(
            name='ServerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.server')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_name', 'external_id'), name='uq_source_external')],
            },
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['ip_address', 'port'], name='idx_server_ip_port'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['game_version'], name='idx_server_version'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['edition'], name='idx_server_edition'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['country'], name='idx_server_country'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['online_players'], name='idx_server_online'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['max_players'], name='idx_server_max'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['votes'], name='idx_server_votes'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['created_at'], name='idx_server_created'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_server_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
