# Generated by Django 5.2.2 on 2025-07-02 08:56

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    username = settings.SUPER_USER_USERNAME
    password = settings.SUPER_USER_PASSWORD
    if not User.objects.filter(username=username).exists():
        user = User()
        user.username = username
        user.email = username
        user.password = make_password(password)
        user.is_superuser = True
        user.is_staff = True
        user.save()


def reverse_create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    username = settings.SUPER_USER_USERNAME
    if User.objects.filter(username=username).exists():
        User.objects.filter(username=username).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=reverse_create_superuser),
    ]
