# Generated by Django 5.2.2 on 2025-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="motd",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="server",
            name="version",
        ),
        migrations.AddField(
            model_name="server",
            name="languages",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="versions",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
