# Generated by Django 5.2.2 on 2025-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_server_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="servertag",
            name="relevance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
