# Generated by Django 5.2.2 on 2025-06-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_servertag_relevance"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
