# Generated by Django 5.2.2 on 2025-06-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_server_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="port",
        ),
    ]
