# Generated by Django 5.2.2 on 2025-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_server_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="edition",
            field=models.CharField(
                choices=[
                    ("java", "Java Edition"),
                    ("bedrock", "Bedrock Edition"),
                    ("both", "Java + Bedrock"),
                ],
                default="java",
                max_length=10,
            ),
        ),
    ]
