# Generated by Django 5.2.2 on 2025-06-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_server_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="discord",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
